# Config inspiration from https://github.com/patrick-kidger/jaxtyping/blob/main/mkdocs.yml
# and https://github.com/PrefectHQ/Prefect
site_name: Modaic Docs
# site_url: https://modaic-ai.github.io/modaic/docs/
site_url: https://www.modaic.dev/docs/
use_directory_urls: true 
repo_url: https://github.com/modaic-ai/modaic
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
  features: 
    - navigation.instant
    - navigation.prune
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
  
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
            heading_level: 4
            inherited_members: true
            members_order: source
            show_bases: false
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
                  
     
nav: 
  - Home: index.md
  - API Reference:
      - PrecompiledAgent: reference/precompiled_agent.md
      - Databases:
          - VectorDatabase: reference/databases/vector_database.md
          - SQLDatabase: reference/databases/sql_database.md
      - Context:
          - Table: reference/context/table.md
          - Text: reference/context/text.md
          - SerializedContext: reference/context/serialized_context.md
          - Context: reference/context/context.md
  - Guides:
      - Context Engineering: guides/context_engineering.md
      - Custom Context: guides/custom_context.md
  - Integrations: integrations/index.md
  - Cookbooks: cookbook/index.md

extra:
  base_path: /docs