site_name: Modaic Docs
site_url: https://modaic.ai
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
  features: 
    - navigation.instant
    - navigation.prune
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
  
markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
          options:
              docstring_style: google
              show_source: true
              show_root_heading: true
              heading_level: 3
              members_order: source
              separate_signature: false
              show_category_heading: true
              show_symbol_type_heading: true
              show_docstring_parameters: true
              show_signature_annotations: true
              unwrap_annotated: true
              annotations_path: brief
              docstring_section_style: table
              merge_init_into_class: true
              rendering:
                  html_meta: false
                  
     
nav: 
  - Home: index.md
  - API Reference:
      - PrecompiledAgent: reference/precompiled_agent.md
      - Databases:
          - VectorDatabase: reference/databases/vector_database.md
          - SQLDatabase: reference/databases/sql_database.md
      - Context:
          - Table: reference/context/table.md
          - Text: reference/context/vector.md
          - SerializedContext: reference/context/serialized_context.md
          - Context: reference/context/context.md
  - Tutorials:
      - Getting Started: tutorials/start.md
  - Integrations: integrations/index.md
  - Cookbook: cookbook/index.md