name: ci
on:
  push:
    branches: [master, main]
permissions:
  contents: write
  pull-requests: write

jobs:
  pydoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Setup uv
        uses: astral-sh/setup-uv@v4
      - name: Sync dependencies with uv (all groups, locked)
        run: uv sync --all-groups --frozen
      - name: Generate docs
        run: PYTHONPATH=src uv run pydoc-markdown pydoc-markdown.yaml --package modaic
      - name: Commit and push docs to main (using PAT)
        env:
          BUILD_DOCS: ${{ secrets.BUILD_DOCS }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "modaic-bot"
            git config user.email "bot@users.noreply.github.com"
            git add -A
            git commit -m "chore(docs): update generated docs [skip ci]"
            git push https://x-access-token:${BUILD_DOCS}@github.com/modaic-ai/modaic.git HEAD:main
          else
            echo "No changes to commit."
          fi
